ASP.NET_mvc/DemoUserManagement/DemoUserManagement/Controllers/Registration_v2Controller.cs
using DemoUserManagement.Attributes;
using DemoUserManagement.Business;
using DemoUserManagement.Models;
using DemoUserManagement.Util;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace DemoUserManagement.Controllers
{
    public class Registration_v2Controller : Controller
    {
        // GET: UserDetail_v2
        [CustomAuthorize_v2]
        public ActionResult UserDetail_v2(int? userID)
        {
            var model = new UserDetailDTO
            {
                Countries = CountryLogic.GetCountryList(),
                DocumentType = Constants.DocumentType,
                States = new List<StateDTO>(),
                Roles = UserLogic.GetRoleList(),
            };

            if (userID.HasValue)
            {
                var user = UserLogic.GetUserById(userID.Value);

                if (user != null)
                {
                    model = user;
                }
            }

            model.Countries = model.Countries ?? new List<CountryDTO>();

            return View(model);
        }

        [HttpPost]
        public ActionResult GetStates(int countryId)
        {
            var states = StateLogic.GetStateList(countryId);

            return Json(states, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public ActionResult NewUser(UserDetailDTO userDetailDTO)
        {
            try
            {
                int userId = UserLogic.SaveUser(userDetailDTO);

                UserLogic.SaveAddress(userId, userDetailDTO);
                UserLogic.SaveRole(userId);

                var fileDetails = Constants.GetFileSessionDetail();
                if (fileDetails != null)
                {
                    string fileNameOnDisk = fileDetails.fileNameOnDisk;
                    string originalFileName = fileDetails.originalFileName;

                    int documentType = Convert.ToInt32(Request.Form["DocumentDropDown"]);
                    DocumentLogic.InsertDocument(userId, Constants.ObjectType.UserDetail, documentType, fileNameOnDisk, originalFileName);
                }
                else
                {
                    ViewBag.ErrorMessage = "Error in uploading file. Please try again!";
                }

                return RedirectToAction("UserDetail_v2", new { UserID = userId });
            }
            catch (Exception ex)
            {
                ViewBag.ErrorMessage = "Error in Registration, Please try again!!";
                Logger.AddError("NewUser Failed", ex);
                return View("UserDetail_v2", "Registration");
            }
        }

        [HttpPost]
        public ActionResult UploadFile(HttpPostedFileBase file)
        {
            var response = UserLogic.UploadFile(file);
            return Json(response);
        }

        [HttpPost]
        public ActionResult AddNote(int userId, string note, int objectType)
        {
            NoteLogic.AddNote(note, userId, objectType);
            return View();
        }

        public JsonResult IsEmailExists(string email)
        {
            bool isEmailExist = UserLogic.IsEmailExists(email);

            return Json(isEmailExist, JsonRequestBehavior.AllowGet);
        }
    }
}

ASP.NET_mvc/DemoUserManagement/DemoUserManagement/Controllers/UserList_v2Controller.cs
using DemoUserManagement.Attributes;
using DemoUserManagement.Business;
using DemoUserManagement.Models;
using System.Collections.Generic;
using System.Web.Mvc;

namespace DemoUserManagement.Controllers
{
    public class UserList_v2Controller : Controller
    {
        // GET: UserList_v2
        [CustomAuthorize_v2]
        public ActionResult UserList_v2(int? page, string sortColumn, string sortDirection)
        {
            int currentPage = page ?? 1;

            sortColumn = string.IsNullOrEmpty(sortColumn) ? "Name" : sortColumn;
            sortDirection = ToggleSortDirection(sortDirection);

            List<UserDetailDTO> userDetailDTO = UserLogic.GetAllUsers(start: (currentPage - 1) * 10, length: 10, sortColumn: sortColumn, sortDirection: sortDirection);

            int totalPages = UserLogic.GetTotalRecords() / 10;
            foreach (var user in userDetailDTO)
            {
                user.CurrentPage = currentPage;
                user.TotalPages = totalPages;
            }

            ViewBag.SortColumn = sortColumn;
            ViewBag.SortDirection = sortDirection;

            return View(userDetailDTO);
        }

        private string ToggleSortDirection(string currentDirection)
        {
            return currentDirection?.ToUpper() == "ASC" ? "DESC" : "ASC";
        }
    }
}

ASP.NET_mvc/DemoUserManagement/DemoUserManagement/Views/UserList_v2/UserList_v2.cshtml
@model List<DemoUserManagement.Models.UserDetailDTO>

@{
    Layout = "~/Views/Shared/_Layout_v2.cshtml";
}

@{
    ViewBag.Title = "UserList";
}

<table id="UserListTable_v2" class="table table-striped table-bordered">
    <thead class="thead-dark">
        <tr>
            <th>@Html.ActionLink("Sl.No", "UserList_v2", new { page = Model.First().CurrentPage, sortColumn = "Name", sortDirection = ViewBag.SortColumn == "Name" && ViewBag.SortDirection == "ASC" ? "DESC" : "ASC" })</th>
            <th>@Html.ActionLink("Name", "UserList_v2", new { page = Model.First().CurrentPage, sortColumn = "Name", sortDirection = ViewBag.SortColumn == "Name" && ViewBag.SortDirection == "ASC" ? "DESC" : "ASC" })</th>
            <th>@Html.ActionLink("Gender", "UserList_v2", new { page = Model.First().CurrentPage, sortColumn = "Gender", sortDirection = ViewBag.SortColumn == "Gender" && ViewBag.SortDirection == "ASC" ? "DESC" : "ASC" })</th>
            <th>@Html.ActionLink("Email", "UserList_v2", new { page = Model.First().CurrentPage, sortColumn = "Email", sortDirection = ViewBag.SortColumn == "Email" && ViewBag.SortDirection == "ASC" ? "DESC" : "ASC" })</th>
            <th>@Html.ActionLink("Phone Number", "UserList_v2", new { page = Model.First().CurrentPage, sortColumn = "PhoneNumber", sortDirection = ViewBag.SortColumn == "PhoneNumber" && ViewBag.SortDirection == "ASC" ? "DESC" : "ASC" })</th>
            <th>@Html.ActionLink("DOB", "UserList_v2", new { page = Model.First().CurrentPage, sortColumn = "DOB", sortDirection = ViewBag.SortColumn == "DOB" && ViewBag.SortDirection == "ASC" ? "DESC" : "ASC" })</th>
            <th>@Html.ActionLink("Father Name", "UserList_v2", new { page = Model.First().CurrentPage, sortColumn = "FatherName", sortDirection = ViewBag.SortColumn == "FatherName" && ViewBag.SortDirection == "ASC" ? "DESC" : "ASC" })</th>
            <th>@Html.ActionLink("Mother Name", "UserList_v2", new { page = Model.First().CurrentPage, sortColumn = "MotherName", sortDirection = ViewBag.SortColumn == "MotherName" && ViewBag.SortDirection == "ASC" ? "DESC" : "ASC" })</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @{
            var count = (Model.First().CurrentPage - 1) * 10 + 1;
            foreach (var user in Model)
            {
                <tr>
                    <td>@(count++)</td>
                    <td>@(user.FirstName + " " + user.MiddleName + " " + user.LastName)</td>
                    <td>@user.Gender</td>
                    <td>@user.Email</td>
                    <td>@user.PhoneNumber</td>
                    <td>@user.DateOfBirth.ToShortDateString()</td>
                    <td>@user.FatherName</td>
                    <td>@user.MotherName</td>
                    <td><a href="@Url.Action("UserDetail_v2", "Registration_v2", new { UserID = user.UserID })">Edit</a></td>
                </tr>
            }
        }
    </tbody>
</table>

<div id="pagination_v2" class="mt-3">
    <nav aria-label="Page navigation">
        <ul class="pagination justify-content-end">
            <li class="page-item">
                <a class="page-link" href="@Url.Action("UserList_v2", "UserList_v2", new { page = Model.First().CurrentPage - 1, sortColumn = ViewBag.SortColumn, sortDirection = ViewBag.SortDirection })" aria-label="Previous">
                    <span aria-hidden="true">&laquo;</span>
                </a>
            </li>

            @for (int i = 1; i <= Model.First().TotalPages; i++)
            {
                <li class="page-item @(i == Model.First().CurrentPage ? "active" : "")">
                    <a class="page-link" href="@Url.Action("UserList_v2", "UserList_v2", new { page = i, sortColumn = ViewBag.SortColumn, sortDirection = ViewBag.SortDirection })">@i</a>
                </li>
            }

            <li class="page-item">
                <a class="page-link" href="@Url.Action("UserList_v2", "UserList_v2", new { page = Model.First().CurrentPage + 1, sortColumn = ViewBag.SortColumn, sortDirection = ViewBag.SortDirection })" aria-label="Next">
                    <span aria-hidden="true">&raquo;</span>
                </a>
            </li>
        </ul>
    </nav>
</div>