ASP.NET_mvc/AirportFuelInventory/AirportFuelInventory/Controllers/LoginController.cs
using AirportFuelInventory.Attributes;
using AirportFuelInventory.Business;
using AirportFuelInventory.Models;
using AirportFuelInventory.Utils;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using static AirportFuelInventory.Models.Model;

namespace AirportFuelInventory.Controllers
{
    public class LoginController : Controller
    {
        // GET: Login
        [CustomAuthorize]
        public ViewResult Login()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Login(UserDTO model)
        {
            int userID = UserLogic.CheckLogin(model.Email, model.Password);

            if (userID != -1)
            {
                UserSession sessionModel = new UserSession();
                sessionModel.UserId = userID;
                Constants.SessionDetail = sessionModel;
                return RedirectToAction("Dashboard", "Dashboard");
            }
            else
            {
                ViewBag.ErrorMessage = "Invalid credentials. Please try again.";
                return View(model);
            }
        }

        public ActionResult Logout()
        {
            if (Session != null)
            {
                Session.Clear();
            }
            return RedirectToAction("Login", "Login");
        }
    }
}

ASP.NET_mvc/AirportFuelInventory/AirportFuelInventory/Controllers/SignUpController.cs
using AirportFuelInventory.Attributes;
using AirportFuelInventory.Business;
using AirportFuelInventory.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using static AirportFuelInventory.Models.Model;

namespace AirportFuelInventory.Controllers
{
    public class SignUpController : Controller
    {
        // GET: SignUp
        [CustomAuthorize]
        public ViewResult SignUp()
        {
            return View();
        }

        [CustomAuthorize]
        public ActionResult NewUser(UserDTO userDTO)
        {
            bool registrationSuccess = UserLogic.NewUser(userDTO);
            if (registrationSuccess)
            {
                return RedirectToAction("Login", "Login");
            }
            else
            {
                ViewBag.ErrorMessage = "Failed to register";
                return View();
            }
        }

        [CustomAuthorize]
        public JsonResult IsEmailExist(string email)
        {
            bool isEmailExist = UserLogic.IsEmailExist(email);
            return Json(isEmailExist);
        }
    }
}

ASP.NET_mvc/AirportFuelInventory/AirportFuelInventory/Views/Login/Login.cshtml
@model AirportFuelInventory.Models.Model.UserDTO

@{
    ViewBag.Title = "Login";
}

@if (!string.IsNullOrEmpty(ViewBag.ErrorMessage))
{
    <p style="color: red;">@ViewBag.ErrorMessage</p>
}

<div class="m-5">
    <div class="border rounded">
        <div class="d-flex align-items-center">
            <img src="~/Images/airport.jpg" class="img-fluid pe-5" />
            <div>
                @using (Html.BeginForm("Login", "Login", FormMethod.Post))
                {
                    @Html.AntiForgeryToken()

                    <div class="form-group">
                        @Html.LabelFor(m => m.Email)
                        @Html.TextBoxFor(m => m.Email, new { @class = "form-control mt-2 mb-2 rounded" })
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(m => m.Password)
                        @Html.PasswordFor(m => m.Password, new { @class = "form-control mt-2 mb-2" })
                    </div>

                    <button class="btn btn-primary">Login</button>
                    @Html.ActionLink("New User", "SignUp", "SignUp", null, new { @class = "btn btn-primary" })
                }

            </div>
        </div>
    </div>
</div>