ASP.NET_mvc/AirportFuelInventory/AirportFuelInventory/Controllers/AirportController.cs
using AirportFuelInventory.Attributes;
using AirportFuelInventory.Business;
using AirportFuelInventory.Models;
using AirportFuelInventory.Utils;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using static AirportFuelInventory.Models.Model;

namespace AirportFuelInventory.Controllers
{
    public class AirportController : Controller
    {
        // GET: AirportList
        [CustomAuthorize]
        public ViewResult AirportList(int? page)
        {
            int currentPage = page ?? 1;
            var model = AirportLogic.GetAirportList(start: (currentPage - 1) * 5, length: 5);

            double totalRecords = AirportLogic.GetTotalRecords() / 5.0;
            int totalPages = Convert.ToInt32(totalRecords);


            foreach (var airport in model)
            {
                airport.Pagination = new Pagination();
                airport.Pagination.CurrentPage = currentPage;
                airport.Pagination.TotalPages = totalPages;
            }

            return View(model);
        }

        [CustomAuthorize]
        public ViewResult AddAirport(int? Airport_Id)
        {
            var model = new AirportDTO();
            if (Airport_Id.HasValue)
            {
                var airport = AirportLogic.GetAirportDetailById(Convert.ToInt32(Request.QueryString["Airport_Id"]));

                if (airport != null)
                {
                    model = airport;
                }
            }

            return View(model);
        }

        [CustomAuthorize]
        public ActionResult NewAirport(AirportDTO airportDTO)
        {
            AirportLogic.NewAirport(airportDTO);
            return RedirectToAction("AirportList");
        }
    }
}

ASP.NET_mvc/AirportFuelInventory/AirportFuelInventory/Views/Airport/AddAirport.cshtml
@model AirportFuelInventory.Models.Model.AirportDTO

@{
    ViewBag.Title = "AddAirport";
}

@using (Html.BeginForm("NewAirport", "Airport", FormMethod.Post))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group mb-3">
            @Html.LabelFor(model => model.Airport_name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Airport_name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Airport_name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group mb-3">
            @Html.LabelFor(model => model.Fuel_Capacity, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Fuel_Capacity, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Fuel_Capacity, "", new { @class = "text-danger" })
            </div>
        </div>

        <div>
            <button type="submit" class="btn btn-primary" id="AddAirportButton">Add</button>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "AirportList")
</div>

ASP.NET_mvc/AirportFuelInventory/AirportFuelInventory/Views/Airport/AirportList.cshtml
@model List<AirportFuelInventory.Models.Model.AirportDTO>
@{
    ViewBag.Title = "AirportList";
}
<h2>AirportList</h2>

<div>
    @if (Model != null)
    {
        <table class="table">
            <thead>
                <tr>
                    <th>Sl.No</th>
                    <th>@Html.DisplayNameFor(model => Model.First().Airport_name)</th>
                    <th>@Html.DisplayNameFor(model => Model.First().Fuel_Capacity)</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @{
                    var count = (Model.First().Pagination.CurrentPage - 1) * 10 + 1;
                    foreach (var airport in Model)
                    {
                        <tr>
                            <td>@(count++)</td>
                            <td>@airport.Airport_name</td>
                            <td>@airport.Fuel_Capacity</td>
                            <td><a href="@Url.Action("AddAirport", "Airport", new { Airport_Id = airport.Airport_id })">Edit</a></td>
                        </tr>

                    }
                }
            </tbody>
        </table>
    }
    else
    {
        <p>No airports available</p>
    }
</div>

<div id="pagination_v2" class="mt-3">
    <nav aria-label="Page navigation">
        <ul class="pagination justify-content-end">
            <li class="page-item">
                <a class="page-link" href="@Url.Action("AirportList", "AirportList", new { page = Model.First().Pagination.CurrentPage - 1})" aria-label="Previous">
                    <span aria-hidden="true">&laquo;</span>
                </a>
            </li>

            <li class="page-item">
                <a class="page-link" href="@Url.Action("AirportList", "AirportList", new { page = Model.First().Pagination.CurrentPage + 1 })" aria-label="Next">
                    <span aria-hidden="true">&raquo;</span>
                </a>
            </li>
        </ul>
    </nav>
</div>

<p>
    @Html.ActionLink("Add Airport", "AddAirport")
</p>